/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package main.java.java.baseball;

import java.util.Scanner;


public class App {
    public String getGreeting() {
        return "Hello world.";
    }
    public static String createRandomNum(){
        String random="";
        while(random.length()<3){
            String temp=String.valueOf((int)(Math.random() *9 +1));
            if(!random.contains(temp)){random+=temp;}
        }
        System.out.println("랜덤변수: "+random);
        return random;
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        Scanner sc = new Scanner(System.in);
        do{
            System.out.println("숫자를 입력해 주세요.");
            int key= sc.nextInt();
            String random=createRandomNum();
            break;
        }while(true);
    }
}
